---

- name: Ensure Nginx YUM repository is configured so that the latest version is installed
  copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo

- name: Ensure service is installed
  yum: name=nginx state=present

- name: Update nginx.conf
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf backup=yes
  notify: reload nginx

- name: Ensure sites-available and sites-enabled directories exist
  file: dest={{ item }} state=directory
  with_items:
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled

- name: Ensure default virtual host is available
  command: cp /etc/nginx/conf.d/default.conf /etc/nginx/sites-available/default 
           creates=/etc/nginx/sites-available/default
  notify: reload nginx

- name: Ensure default virtual host is enabled
  file: src=/etc/nginx/sites-available/default dest=/etc/nginx/sites-enabled/default state=link
  notify: reload nginx

- name: Ensure conf.d directory does not exist
  file: dest=/etc/nginx/conf.d state=absent

- name: Ensure service is started and that it always starts on boot
  service: name=nginx state=started enabled=yes
